/**
 * Team-friendly workspace setup, run by `/docs add` and `/docs setup`.
 *
 * Shared in git:   .pi/docs.json (sources), the package declaration in .pi/settings.json,
 *                  a path-free note in AGENTS.md.
 * Never in git:    the downloaded mirror (per-user cache) -> `.pi/docs-mirror/` in .gitignore.
 *
 * Every step is idempotent: it only writes when something is missing.
 */

import * as fs from "node:fs";
import * as path from "node:path";

export const PACKAGE_SOURCE = "npm:@raffaelenatale/pi-docs-sync";
export const MIRROR_IGNORE_ENTRY = ".pi/docs-mirror/";
export const AGENTS_BEGIN = "<!-- BEGIN pi-docs-sync -->";
export const AGENTS_END = "<!-- END pi-docs-sync -->";

export const AGENTS_BLOCK = [
	AGENTS_BEGIN,
	"## Local documentation (pi-docs-sync)",
	"",
	"Official docs for this project's libraries are mirrored locally by pi-docs-sync; the sources are listed in `.pi/docs.json`.",
	"Use `docs_list`, `docs_search` and `docs_read` before any web fetch.",
	`If those tools are missing, trust the project (the package is declared in \`.pi/settings.json\`) or run \`pi install ${PACKAGE_SOURCE}\`.`,
	AGENTS_END,
].join("\n");

export type SetupStep = "gitignore" | "settings" | "agents";
export interface SetupResult {
	changed: SetupStep[];
	skipped: { step: SetupStep; reason: string }[];
}

/** Pure: returns the new .gitignore text, or null when the mirror is already ignored. */
export function addGitignoreEntry(text: string): string | null {
	const lines = text.split(/\r?\n/).map((l) => l.trim());
	const covered = [".pi/docs-mirror", ".pi/docs-mirror/", "/.pi/docs-mirror", "/.pi/docs-mirror/", ".pi/", ".pi", "/.pi/", "/.pi"];
	if (lines.some((l) => covered.includes(l))) return null;
	const prefix = text.length === 0 || text.endsWith("\n") ? text : `${text}\n`;
	return `${prefix}\n# pi-docs-sync mirror (per-user cache, regenerated by sync)\n${MIRROR_IGNORE_ENTRY}\n`;
}

function packageEntrySource(entry: unknown): string | undefined {
	if (typeof entry === "string") return entry;
	if (entry && typeof entry === "object" && typeof (entry as { source?: unknown }).source === "string") return (entry as { source: string }).source;
	return undefined;
}

/** Pure: returns the new settings object, or null when pi-docs-sync is already declared. */
export function addPackageDeclaration(settings: Record<string, unknown>): Record<string, unknown> | null {
	const packages = Array.isArray(settings.packages) ? settings.packages : [];
	if (packages.some((p) => /pi-docs-sync/.test(packageEntrySource(p) ?? ""))) return null;
	return { ...settings, packages: [...packages, PACKAGE_SOURCE] };
}

/** Pure: returns the new AGENTS.md text, or null when the block is already up to date. */
export function upsertAgentsBlock(text: string): string | null {
	const start = text.indexOf(AGENTS_BEGIN);
	const end = text.indexOf(AGENTS_END);
	if (start !== -1 && end > start) {
		const next = text.slice(0, start) + AGENTS_BLOCK + text.slice(end + AGENTS_END.length);
		return next === text ? null : next;
	}
	if (text.trim().length === 0) return `${AGENTS_BLOCK}\n`;
	const prefix = text.endsWith("\n") ? text : `${text}\n`;
	return `${prefix}\n${AGENTS_BLOCK}\n`;
}

function readText(filePath: string): string | null {
	try {
		return fs.readFileSync(filePath, "utf8");
	} catch {
		return null;
	}
}

function writeText(filePath: string, text: string): void {
	fs.mkdirSync(path.dirname(filePath), { recursive: true });
	const tmp = `${filePath}.tmp-${process.pid}`;
	fs.writeFileSync(tmp, text, "utf8");
	fs.renameSync(tmp, filePath);
}

/** Apply the three setup steps to the workspace at `cwd`. */
export function setupWorkspace(cwd: string): SetupResult {
	const result: SetupResult = { changed: [], skipped: [] };

	// 1. .gitignore — only inside a git checkout root.
	if (fs.existsSync(path.join(cwd, ".git"))) {
		const gitignorePath = path.join(cwd, ".gitignore");
		const next = addGitignoreEntry(readText(gitignorePath) ?? "");
		if (next !== null) {
			writeText(gitignorePath, next);
			result.changed.push("gitignore");
		}
	} else {
		result.skipped.push({ step: "gitignore", reason: "not a git checkout root" });
	}

	// 2. .pi/settings.json — declare the package so teammates get it after trusting the project.
	const settingsPath = path.join(cwd, ".pi", "settings.json");
	const settingsText = readText(settingsPath);
	let settings: Record<string, unknown> | null = {};
	if (settingsText !== null) {
		try {
			const parsed: unknown = JSON.parse(settingsText);
			settings = parsed && typeof parsed === "object" && !Array.isArray(parsed) ? (parsed as Record<string, unknown>) : null;
		} catch {
			settings = null;
		}
	}
	if (settings === null) {
		result.skipped.push({ step: "settings", reason: ".pi/settings.json is not a valid JSON object" });
	} else {
		const next = addPackageDeclaration(settings);
		if (next !== null) {
			writeText(settingsPath, `${JSON.stringify(next, null, 2)}\n`);
			result.changed.push("settings");
		}
	}

	// 3. AGENTS.md — path-free note; falls back to CLAUDE.md when only that exists.
	const agentsPath = path.join(cwd, "AGENTS.md");
	const claudePath = path.join(cwd, "CLAUDE.md");
	const target = !fs.existsSync(agentsPath) && fs.existsSync(claudePath) ? claudePath : agentsPath;
	const nextAgents = upsertAgentsBlock(readText(target) ?? "");
	if (nextAgents !== null) {
		writeText(target, nextAgents);
		result.changed.push("agents");
	}

	return result;
}

export function formatSetupResult(result: SetupResult): string {
	const labels: Record<SetupStep, string> = {
		gitignore: `.gitignore: ignores ${MIRROR_IGNORE_ENTRY}`,
		settings: `.pi/settings.json: declares ${PACKAGE_SOURCE}`,
		agents: "AGENTS.md: pi-docs-sync note",
	};
	const lines = result.changed.map((step) => `+ ${labels[step]}`);
	for (const s of result.skipped) lines.push(`- ${s.step} skipped: ${s.reason}`);
	return lines.length > 0 ? `pi-docs-sync workspace setup:\n${lines.join("\n")}` : "pi-docs-sync workspace setup: already up to date.";
}
